services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - '9229:9229'
    command: yarn start:debug
    depends_on:
      - postgres-db
      - redis-db
    env_file:
      - .env/.env
  nginx:
    image: nginx:stable-alpine
    ports:
      - '3333:80'
      - '4000:4000'
    volumes:
      - ./nginx_conf.d/dev.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api

  postgres-db:
    image: postgres:latest
    env_file:
      - .env/.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  redis-db:
    image: redis:alpine
    ports:
      - '6379:6379'

volumes:
  pg_data:
