export const databaseSchema = {
  DATABASE_NAME: 'POSTGRES_DB',
  DATABASE_HOST: 'POSTGRES_HOST',
  DATABASE_PORT: 'POSTGRES_PORT',
  DATABASE_USER: 'POSTGRES_USERNAME',
  DATABASE_PASSWORD: 'POSTGRES_PASSWORD',
};

export const config = {
  APP_SECRET: 'APP_SECRET',
  EXPIRATION_TIME: 'EXPIRATION_TIME',
};
